apiVersion: apps/v1
kind: Deployment
metadata:
  name: abilists-tomcat
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: abilists-tomcat
  template:
    metadata:
      labels:
        run: abilists-tomcat
    spec:
      containers:
      - name: abilists-tomcat
        image: abilists/tomcat8.5:1.3.5
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: abilists-volume
          mountPath: /home/njoonk/.abilists
#          mountPath: ~/.abilists
      volumes:
      - name: abilists-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: abilists-service
spec:
  selector:
    run: abilists-tomcat
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  externalIPs:
  - 192.168.0.72

