apiVersion: v1
kind: Pod
metadata:
  name: abilists-tomcat
spec:
  containers:
  - name: abilists-tomcat
    image: abilists/tomcat8.5:1.3.5
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: abilists-volume
      mountPath: ~/.abilists
  volumes:
  - name: abilists-volume
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: abilists-service
spec:
  type: NodePort
  selector:
    name: abilists-tomcat
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  externalIPs:
  - 192.168.0.72

