apiVersion: apps/v1
kind: Deployment
metadata:
  name: abilists-tomcat
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abilists-tomcat
  template:
    metadata:
      labels:
        app: abilists-tomcat
    spec:
      containers:
      - name: abilists-tomcat
        image: abilists/tomcat8.5:1.3.5
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: abilists-volume
          mountPath: /root/.abilists
      volumes:
      - name: abilists-volume
        emptyDir: {}
