apiVersion: apps/v1
kind: Deployment
metadata:
  name: abilists-tomcat
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: abilists/tomcat8.5
        image: abilists/tomcat8.5:1.3.5
        volumeMounts:
        - name: abilists-volume
          mountPath: ~/.abilists
      volumes:
      - name: abilists-volume
        emptyDir: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: abilists-pod 
spec:
  containers:
  - name: abilists/tomcat8.5
    image: abilists/tomcat8.5:1.3.5
    ports:
    - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: abilists-service
  labels:
    run: abilists-service
  namespace: default
spec:
  selector:
    app: abilists-pod
  ports:
  - port: 80
    targetPort: 8080
